import turtle
screen=turtle.Screen()
screen.screensize(500,500)
screen.bgcolor("hotpink")
t=turtle.Turtle()
#intro screen
t.penup()
t.goto(0,100)
t.pendown()
t.pencolor('red')


t.write('All about me ', font=("Arial", 50, "bold"), align="center")
t.penup()
t.goto(0,50)
t.pendown()
t.write('Press enter to continue', font=("Arial", 20, "bold"), align="center")
round = input("Press Enter to Continue: ")
t.clear()
screen.bgcolor("purple")
t2=turtle.Turtle()

t2.goto(0,100)
t2.pendown()
t2.pencolor('white')
t2.write('My 3 favorite foods', font=("Arial", 30, "bold"), align="center")
t2.penup()
t2.goto(0,50)
t2.pendown()
t2.pencolor('white')
t2.write('1.Spicy Chicken Sandwhich', font=("Arial", 20, "bold"), align="center")
t2.penup()
t2.goto(0,25)
t2.pendown()
t2.pencolor('white')
t2.write('2.Pepperoni Pizza', font=("Arial", 15, "bold"), align="center")
screen=turtle.Screen()
screen.addshape('pizzaaa 2.gif')
t2.penup()
t2.shape('pizzaaa 2.gif')
t2.goto(-150,-100)
t2.stamp()

t2.hideturtle()
screen=turtle.Screen()
screen.addshape('chicken sandwhich.gif')
t2.penup()
t2.shape('chicken sandwhich.gif')
t2.goto(150,-100)
t2.stamp()

t2.penup()
t2.goto(0,5)
t2.pendown()
t2.pencolor('white')
t2.write('3.Alfredo Pasta', font=("Arial", 15, "bold"), align="center")
t2.penup()
t2.goto(-300,-350)
t2.pendown()
t2.pencolor('white')
t2.fillcolor("white")
t2.begin_fill()
for _ in range(3):
    t2.forward(100)
    t2.left(120)
round = input("Press Enter to Continue: ")

t2.clear()
screen.bgcolor("lightpink")
t3=turtle.Turtle()
t3.penup()
t3.goto(0,180)
t3.pendown()
t3.pencolor('blue')
t3.write('My hobbies', font=("Arial", 35, "bold"), align="center")
t3.penup()
t3.hideturtle
t3.pencolor('blue')
t3.goto(-180,140)
t3.write('1.Cooking/Baking', font=("Arial", 30, "bold"), align="center")
t3.goto(-180,100)
t3.write('2.Painting', font=("Arial", 30, "bold"), align="center")
t3.goto(-180,60)
t3.write('3.Drawing', font=("Arial", 30, "bold"), align="center")
t3.goto(-180,20)
t3.write('4.Reading', font=("Arial", 30, "bold"), align="center")
t3.penup()
screen.addshape('baking.gif')
t3.shape('baking.gif')
t3.goto(200,90)
t3.stamp()
t3.hideturtle()
t3.penup()
screen.addshape('painting.gif')
t3.shape('painting.gif')
t3.goto(50,-50)
t3.stamp()
t3.penup()
screen.addshape('reading.gif')
t3.shape('reading.gif')
t3.goto(200,-50)
t3.stamp()

t3.penup()
t3.goto(-300,-200)
t3.pendown()
t2.fillcolor("blue")
t3.pencolor('blue')
t3.fillcolor("blue")
t3.begin_fill()

for _ in range(4):
    t3.forward(100)
    t3.right(90)
    t3.end_fill()


round = input("Press Enter to Continue: ")

t3.clear()
t3.hideturtle()

screen.bgcolor("tan")
t4=turtle.Turtle()
t4.penup()
t4.goto(0,180)
t4.pendown()
t4.pencolor('darkgreen')
t4.write('My Favorite Movie', font=("Arial", 35, "bold"), align="center")
t4.penup()
screen.addshape('lion king.gif')
t4.shape('lion king.gif')
t4.goto(0,0)
t4.stamp()
t4.penup()

round = input("Press Enter to Continue: ")
t4.clear()
t4.hideturtle()
screen.bgcolor("lightblue")
t5=turtle.Turtle()
t5.penup()
t5.goto(0,180)
t5.pendown()
t5.pencolor('yellow')
t5.write('My Favorite Sport is Track', font=("Arial", 35, "bold"), align="center")
screen.addshape('Track (1).gif')
t5.shape('Track (1).gif')
t5.goto(0,0)
t5.stamp()
t5.penup()




turtle.done()
